# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.14' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code


steps:
- task: GoTool@0
  inputs:
    version: '1.14'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls -al /usr/local'
- task: Bash@3
  inputs:
      targetType: 'inline'
      script: |
          echo 'Compiling and building'
          sh 'go get -u golang.org/x/lint/golint'
          sh 'go get -t -d -v && go build -v -o App'