version: 0.0

os: linux

files:
  - source: /aws-codedeploy
    destination: /app/
  - source: /index.html
    destination: /app/
  - source: /config.json
    destination: /app/

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 180
      runas: ec2-user
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 180
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 180
      runas: ec2-user
